title: Daniel L Perret, PhD
logo: "/images/dperret_webpic_lowresclip.jpg?raw=true"
description: >
  Forest ecologist, biogeographer, and dendrochronologist living and working in Missoula, MT.
  Spatial Scientist with The Nature Conservancy.

# Social & Contact
email: daniel.perret@tnc.org
github_username: daniel-perret
google_scholar: "https://scholar.google.com/citations?user=E_yUYQkAAAAJ&hl=en"

# Analytics
google_analytics: UA-000000-0

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
